/**
 * Songs API
 * Test version of the api
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.Song;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Album {
  
  @SerializedName("id")
  private Integer id = null;
  @SerializedName("songs")
  private List<Song> songs = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("artist")
  private Integer artist = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<Song> getSongs() {
    return songs;
  }
  public void setSongs(List<Song> songs) {
    this.songs = songs;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getArtist() {
    return artist;
  }
  public void setArtist(Integer artist) {
    this.artist = artist;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Album album = (Album) o;
    return (this.id == null ? album.id == null : this.id.equals(album.id)) &&
        (this.songs == null ? album.songs == null : this.songs.equals(album.songs)) &&
        (this.name == null ? album.name == null : this.name.equals(album.name)) &&
        (this.artist == null ? album.artist == null : this.artist.equals(album.artist));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.songs == null ? 0: this.songs.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.artist == null ? 0: this.artist.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Album {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  songs: ").append(songs).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  artist: ").append(artist).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
