/**
 * Songs API
 * Test version of the api
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Song {
  
  @SerializedName("id")
  private Integer id = null;
  @SerializedName("title")
  private String title = null;
  @SerializedName("duration")
  private Integer duration = null;
  @SerializedName("stream_url")
  private String streamUrl = null;
  @SerializedName("album")
  private Integer album = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getTitle() {
    return title;
  }
  public void setTitle(String title) {
    this.title = title;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Integer getDuration() {
    return duration;
  }
  public void setDuration(Integer duration) {
    this.duration = duration;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getStreamUrl() {
    return streamUrl;
  }
  public void setStreamUrl(String streamUrl) {
    this.streamUrl = streamUrl;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getAlbum() {
    return album;
  }
  public void setAlbum(Integer album) {
    this.album = album;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Song song = (Song) o;
    return (this.id == null ? song.id == null : this.id.equals(song.id)) &&
        (this.title == null ? song.title == null : this.title.equals(song.title)) &&
        (this.duration == null ? song.duration == null : this.duration.equals(song.duration)) &&
        (this.streamUrl == null ? song.streamUrl == null : this.streamUrl.equals(song.streamUrl)) &&
        (this.album == null ? song.album == null : this.album.equals(song.album));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.title == null ? 0: this.title.hashCode());
    result = 31 * result + (this.duration == null ? 0: this.duration.hashCode());
    result = 31 * result + (this.streamUrl == null ? 0: this.streamUrl.hashCode());
    result = 31 * result + (this.album == null ? 0: this.album.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Song {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  title: ").append(title).append("\n");
    sb.append("  duration: ").append(duration).append("\n");
    sb.append("  streamUrl: ").append(streamUrl).append("\n");
    sb.append("  album: ").append(album).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
